notifications:
  slack: zewo:VjyVCCQvTOw9yrbzQysZezD1
os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install openssl;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get -qq update;
        sudo apt-get -y install libssl-dev;
    fi
install:
  - eval "$(curl -sL https://raw.githubusercontent.com/Zewo/Zewo/5254525d9da56df29346fd76e99529c22034d61d/Scripts/install-swiftenv.sh)"
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      swift build;
      swift build --configuration release;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      swift build -Xlinker -rpath -Xlinker $(pwd)/.build/debug/;
      swift build --configuration release -Xlinker -rpath -Xlinker $(pwd)/.build/release/;
    fi
  - swift test
